version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: widen
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.36
    - 14.14.39
    - 15.0.0
  - dependency-name: js-yaml
    versions:
    - 4.1.0
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
    - 3.4.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.2
    - 4.16.1
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
    - 4.22.0
  - dependency-name: "@actions/core"
    versions:
    - 1.2.7
  - dependency-name: "@vercel/ncc"
    versions:
    - 0.28.0
    - 0.28.1
    - 0.28.2
  - dependency-name: eslint
    versions:
    - 7.22.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.5
    - 24.1.8
    - 24.1.9
    - 24.3.1
  - dependency-name: typescript
    versions:
    - 4.2.2
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
